services:
  web:
    image: registry.zaretti.be/nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - /data:/data
      - /etc/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - php7
      - php5
  php7:
    image: registry.zaretti.be/php:7.4
    restart: unless-stopped
    volumes:
      - /var/www:/var/www
    networks:
      - default
      - backend
  php5:
    image: registry.zaretti.be/php:5.6
    restart: unless-stopped
    volumes:
      - /var/www:/var/www
    networks:
      - default
      - backend
networks:
  backend:
    external:
      name: backend
