services:
  web:
    image: registry.zaretti.be/nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - /mnt/data:/mnt/data
      - /etc/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/pterodactyl:/var/lib/pterodactyl
    links:
      - php7
      - php5
      - mariadb
  php7:
    image: registry.zaretti.be/php:7.4
    restart: unless-stopped
    volumes:
      - /var/www:/var/www
      - /opt/php/php7.ini:/usr/local/etc/php/php.ini
    networks:
      - default
      - backend
  php5:
    image: registry.zaretti.be/php:5.6
    restart: unless-stopped
    volumes:
      - /var/www:/var/www
      - /opt/php/php5.ini:/usr/local/etc/php/php.ini
    networks:
      - default
      - backend
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_USER=kossolax
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    volumes:
      - /opt/database:/var/lib/mysql
    networks:
      - default
      - backend
networks:
  backend:
    external:
      name: backend
