web:
  image: localhost:5000/kossolax/nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www:/var/www
    - /etc/nginx:/etc/nginx
    - /etc/letsencrypt:/etc/letsencrypt
  links:
    - php7
    - php5

php7:
  image: localhost:5000/kossolax/php:7.4
  volumes:
    - /var/www:/var/www

php5:
  image: localhost:5000/kossolax/php:5.6
  volumes:
    - /var/www:/var/www