name: CI
on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.zaretti.be
          username: kossolax
          password: ${{ secrets.PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: nginx/
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/kossolax/nginx:latest
