name: CI
on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.zaretti.be
          username: kossolax
          password: ${{ secrets.PASSWORD }}
      -
        name: WEB
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/nginx:latest
      -
        name: PHP 7.4
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php/Dockerfile-7.4
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/php:7.4
      -
        name: PHP 5.6
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php/Dockerfile-5.6
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/php:5.6
      -
        name: PXE
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pxe/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/pxe:latest
      -
        name: Phabricator
        uses: docker/build-push-action@v2
        with:
          context: ./phabricator/
          file: ./phabricator/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/phabricator:latest
      -
        name: Desktop
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./desktop/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.zaretti.be/desktop:latest
