name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file nginx/Dockerfile --tag home.zaretti.be:5000/kossolax/nginx:latest && docker image push home.zaretti.be:5000/kossolax/nginx:latest
      
